import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

// ─── Types ────────────────────────────────────────────────────────────────────
export type AdminLang = 'ru' | 'ro';

// ─── Translations ─────────────────────────────────────────────────────────────
const T = {
  ru: {
    nav: {
      dashboard: 'Дашборд',
      requests:   'Заявки',
      clients:    'Клиенты',
      products:   'Товары',
      brands:     'Бренды',
      banners:    'Баннеры',
      categories: 'Категории',
      featured:   'Рекомендуемые',
      import:     'Импорт',
      site:       'Сайт',
      logout:     'Выйти',
    },
    common: {
      save:        'Сохранить',
      saving:      'Сохранение...',
      cancel:      'Отмена',
      delete:      'Удалить',
      deleting:    'Удаление...',
      edit:        'Редактировать',
      add:         'Добавить',
      search:      'Поиск',
      refresh:     'Обновить',
      loading:     'Загрузка...',
      noData:      'Нет данных',
      export:      'Экспорт',
      error:       'Ошибка',
      all:         'Все',
      active:      'Активные',
      inactive:    'Неактивные',
      new:         'Новый',
      name:        'Имя',
      email:       'Email',
      phone:       'Телефон',
      company:     'Компания',
      address:     'Адрес',
      notes:       'Заметки',
      date:        'Дата',
      type:        'Тип',
      status:      'Статус',
      price:       'Цена',
      stock:       'Склад',
      category:    'Категория',
      brand:       'Бренд',
      description: 'Описание',
      image:       'Изображение',
      of:          'из',
      selected:    'выбрано',
      clearSel:    'Снять выбор',
      noResults:   'Ничего не найдено',
      openInSite:  'Открыть на сайте',
    },
    clients: {
      title:            'Клиенты',
      searchPlaceholder:'Поиск по имени, email, компании...',
      filterCompany:    'Юрлица',
      filterIndividual: 'Физлица',
      exportCsv:        'CSV',
      copyEmail:        'Копировать email',
      newsletter:       'Рассылка',
      typeCompany:      'Юрлицо',
      typeIndividual:   'Физлицо',
      deleteConfirm:    'Удалить клиента?',
      deleted:          'Клиент удалён',
      errorDelete:      'Ошибка удаления',
      copied:           'Скопировано',
      clientsWord:      'клиентов',
      clearSel:         'Снять выбор',
      noData:           'Клиентов пока нет. После первой регистрации они появятся здесь.',
      noResults:        'Ничего не найдено',
      newsletterTitle:  'Рассылка предложения',
      recipients:       'Получатели',
      selectedLabel:    'выбранные',
      allLabel:         'все в списке',
      emailSubject:     'Тема письма',
      openInEmail:      'Открыть в почте',
      copyBcc:          'Скопировать BCC',
      bccNote:          'Кнопка откроет ваш почтовый клиент (Outlook / Gmail) с заполненными адресами в поле BCC. Письмо нужно написать и отправить вручную. Для массовой рассылки используйте MailChimp / SendGrid.',
      colName:          'Имя / Компания',
      colEmail:         'Email',
      colPhone:         'Телефон',
      colType:          'Тип',
      colDate:          'Дата',
      colAddress:       'Адрес',
      colNotes:         'Заметки',
      colId:            'ID',
    },
    requests: {
      title:            'Заявки',
      searchPlaceholder:'Поиск по имени, email, компании...',
      statusNew:        'Новая',
      statusInProgress: 'В работе',
      statusDone:       'Выполнена',
      statusCancelled:  'Отменена',
      deleteConfirm:    'Удалить заявку?',
      deleted:          'Заявка удалена',
      noData:           'Заявок пока нет',
      noResults:        'Ничего не найдено',
      items:            'товаров',
      totalPrice:       'Сумма',
      deliveryAddress:  'Адрес доставки',
      orderItems:       'Состав заявки',
      clientName:       'Клиент',
      clientCompany:    'Компания',
      colDate:          'Дата',
      colStatus:        'Статус',
      colTotal:         'Итого',
      colItems:         'Товаров',
      noTableMsg:       'Таблица',
      noTableDesc:      'не существует в Supabase. Запустите SQL ниже:',
      showSql:          'Показать SQL',
      hideSql:          'Скрыть SQL',
      statusUpdated:    'Статус обновлён',
      filterAll:        'Все',
      cartItems:        'Товары',
      total:            'Итого',
      notes:            'Примечание',
      clientComment:    'Комментарий клиента',
      adminComment:     'Комментарий администратора',
      adminCommentPlaceholder: 'Добавить комментарий...',
      saveComment:      'Добавить комментарий',
      noComment:        '—',
      delete:           'Удалить заявку',
      client:           'Клиент',
      status:           'Статус',
      nothingFound:     'Ничего не найдено',
      empty:            'Заявок пока нет',
      noItems:          'Нет товаров',
    },
    products: {
      title:          'Товары',
      newBtn:         'Новый товар',
      editTitle:      'Редактировать товар',
      newTitle:       'Новый товар',
      nameRoLabel:    'Название RO',
      nameRuLabel:    'Название RU',
      namePlaceholder:'Название на румынском',
      nameRuPlaceholder:'Название на русском',
      descRoLabel:    'Описание RO',
      descRuLabel:    'Описание RU',
      descRoPlaceholder:'Подробное описание на румынском...',
      descRuPlaceholder:'Подробное описание на русском...',
      subcategory:    'Подкатегория',
      noSubcat:       '— нет —',
      unit:           'Единица',
      sku:            'Артикул / SKU',
      priceMdl:       'Цена MDL',
      stockQty:       'Остаток (шт)',
      activeLabel:    'Активный (виден)',
      inactiveLabel:  'Неактивный (скрыт)',
      featuredLabel:  'Рекомендуемый на главной',
      notFeaturedLabel:'Не рекомендуемый',
      youtubeUrl:     'URL YouTube',
      imageNote:      'макс 4 · первое = главное',
      imageMainBadge: 'Главное',
      imageSlot:      'Фото',
      deleteProduct:  'Удалить товар',
      deleteConfirm:  'Вы уверены? Товар будет удалён навсегда.',
      deleted:        'Товар удалён.',
      saved:          'Товар сохранён!',
      updated:        'Товар обновлён!',
      nameRequired:   'Введите название товара',
      catRequired:    'Выберите категорию',
      allCategories:  'Все категории',
      allFilter:      'Все',
      activeFilter:   'Активные',
      inactiveFilter: 'Неактивные',
      reload:         'Обновить',
      colProduct:     'Товар',
      colCategory:    'Категория',
      colPrice:       'Цена MDL',
      colStock:       'Склад',
      colActive:      'Активный',
      colFeatured:    'Рек.',
      of:             'из',
      noData:         'Товаров не найдено',
      selectCat:      'Выберите...',
      selectSubcat:   'Нет',
      pageProduct:    'Страница товара',
    },
    brands: {
      title:          'Бренды',
      newBtn:         'Новый бренд',
      editTitle:      'Редактировать бренд',
      newTitle:       'Новый бренд',
      nameLabel:      'Название бренда',
      slugLabel:      'Slug (URL)',
      countryRoLabel: 'Страна (RO)',
      countryRuLabel: 'Страна (RU)',
      flagLabel:      'Флаг (эмодзи)',
      foundedLabel:   'Год основания',
      segmentRoLabel: 'Сегмент (RO)',
      segmentRuLabel: 'Сегмент (RU)',
      taglineRoLabel: 'Слоган (RO)',
      taglineRuLabel: 'Слоган (RU)',
      websiteLabel:   'Веб-сайт',
      websiteUrlLabel:'URL сайта',
      descRoLabel:    'Описание (RO)',
      descRuLabel:    'Описание (RU)',
      logoLabel:      'Логотип',
      bannerDesktop:  'Баннер (Desktop)',
      bannerMobile:   'Баннер (Mobile)',
      deleteConfirm:  'Удалить бренд?',
      deleted:        'Бренд удалён',
      saved:          'Бренд сохранён!',
      productsWord:   'товаров',
      noData:         'Брендов пока нет. Добавьте первый.',
      searchPlaceholder:'Поиск бренда...',
      loadLogo:       'Загрузить логотип',
      newBrand:       'Новый бренд',
      editBrand:      'Редактировать бренд',
      brandName:      'Название бренда',
      descriptions:   'Описание',
      countryInfo:    'Страна / Год',
      segment:        'Сегмент / Сайт',
      banners:        'Баннеры',
      active:         'activ',
      hidden:         'ascuns',
      noBrands:       'Брендов пока нет',
      noResults:      'Ничего не найдено',
      saving:         'Сохранение…',
      create:         'Создать бренд',
      save:           'Сохранить',
      delete:         'Удалить',
      founded:        'Год осн.',
    },
    banners: {
      title:          'Баннеры',
      newBtn:         'Новый баннер',
      editTitle:      'Редактировать баннер',
      newTitle:       'Новый баннер',
      deleteConfirm:  'Удалить баннер?',
      deleted:        'Баннер удалён',
      saved:          'Баннер сохранён!',
      titleRoLabel:   'Заголовок (RO)',
      titleRuLabel:   'Заголовок (RU)',
      subtitleRoLabel:'Подзаголовок (RO)',
      subtitleRuLabel:'Подзаголовок (RU)',
      ctaRoLabel:     'Кнопка (RO)',
      ctaRuLabel:     'Кнопка (RU)',
      linkLabel:      'Ссылка',
      sortOrder:      'Порядок',
      activeLabel:    'Активный',
      imageLabel:     'Изображение',
      noData:         'Баннеров пока нет. Создайте первый.',
      noTable:        'Таблица banners не существует в Supabase.',
      noTableDesc:    'Запустите SQL ниже в Supabase Dashboard → SQL Editor:',
      showSql:        'Показать SQL',
      hideSql:        'Скрыть SQL',
    },
    categories: {
      title:          'Категории',
      newCat:         'Новая категория',
      newSub:         'Новая подкатегория',
      editCat:        'Редактировать категорию',
      editSub:        'Редактировать подкатегорию',
      deleteConfirm:  'Удалить?',
      deleted:        'Удалено',
      saved:          'Сохранено',
      nameRoLabel:    'Название (RO)',
      nameRuLabel:    'Название (RU)',
      descRoLabel:    'Описание (RO)',
      descRuLabel:    'Описание (RU)',
      slugLabel:      'Slug',
      sortLabel:      'Порядок сортировки',
      subcategories:  'Подкатегории',
      addSubcat:      'Добавить подкатегорию',
      noData:         'Категорий нет. Создайте первую.',
      noTable:        'Таблицы категорий не сущестуют.',
    },
    featured: {
      title:          'Рекомендуемые',
      searchPlaceholder:'Поиск товара...',
      tabAll:         'Все товары',
      tabFeatured:    'Рекомендуемые',
      allCategories:  'Все категории',
      noFeatured:     'Нет рекомендуемых товаров',
      noResults:      'Ничего не найдено',
      added:          'добавлен в Рекомендуемые',
      removed:        'удалён из Рекомендуемых',
      errorSave:      'Ошибка при сохранении',
      countLabel:     'рекомендуемых',
      reload:         'Обновить',
    },
    import: {
      title:          'Импорт товаров',
      dropzone:       'Перетащите файл .xlsx или .csv, или нажмите для выбора',
      formatNote:     'Поддерживаются форматы .xlsx / .csv',
      preview:        'Предпросмотр',
      importBtn:      'Импортировать',
      importing:      'Импорт...',
      successWord:    'товаров импортировано',
      errorsWord:     'ошибок',
      downloadTemplate:'Скачать шаблон',
      columns:        'Колонки:',
      clearBtn:       'Очистить',
      rowsCount:      'строк в файле',
    },
    hub: {
      productsTitle:  'Товары',
      productsDesc:   'Добавить, редактировать, удалить товары. Загрузить изображения. Управлять остатками, ценами, описаниями.',
      brandsTitle:    'Бренды',
      brandsDesc:     'Управление брендами и производителями спортивного оборудования.',
      bannersTitle:   'Баннеры',
      bannersDesc:    'Управление слайдером на главной странице.',
      categoriesTitle:'Категории',
      categoriesDesc: 'Управление категориями и подкатегориями каталога.',
      featuredTitle:  'Рекомендуемые',
      featuredDesc:   'Выбрать товары для витрины на главной странице.',
      importTitle:    'Импорт',
      importDesc:     'Массовый импорт товаров из Excel/CSV файла.',
      contactsTitle:  'Контакты',
      contactsDesc:   'Телефон, email, адрес, часы работы и ссылки на соцсети сайта.',
      popupTitle:     'Промо-попап',
      popupDesc:      'Всплывающее окно с акцией или важным объявлением на сайте.',
      faqTitle:       'FAQ',
      faqDesc:        'Часто задаваемые вопросы — показываются на странице «О нас».',
      servicesTitle:  'Страницы услуг',
      servicesDesc:   'Тексты, статистика и пакеты страниц «Под ключ» и «Обслуживание».',
      maintenanceTitle:    'Тех. обслуживание',
      maintenanceDesc:     'Контент страницы «Техническое обслуживание» — тарифы, услуги, FAQ.',
      contentPagesTitle:   'Страницы футера',
      contentPagesDesc:    'Редактирование текста страниц: Условия, Доставка, Конфиденциальность.',
      totalLabel:     'Всего товаров',
      activeLabel:    'активных',
      inactiveLabel:  'неактивных',
      featuredLabel:  'рекомендуемых',
      noImageLabel:   'без фото',
      outOfStockLabel:'нет в наличии',
      statsTitle:     'Статистика каталога',
      // tabs
      tabClients:     'Клиенты',
      tabProducts:    'Товары',
      tabContent:     'Контент',
      // client-section cards
      requestsTitle:  'Заявки',
      requestsDesc:   'Просматривать и обрабатывать заявки на покупку от клиентов.',
      clientsTitle:   'Клиенты',
      clientsDesc:    'База зарегистрированных пользователей. Рассылка, экспорт контактов.',
      emailTitle:     'Email-уведомления',
      emailDesc:      'Настройка шаблонов и интеграции EmailJS для автоответов.',
    },
  },

  ro: {
    nav: {
      dashboard: 'Panou',
      requests:  'Cereri',
      clients:   'Clienți',
      products:  'Produse',
      brands:    'Branduri',
      banners:   'Bannere',
      categories:'Categorii',
      featured:  'Recomandate',
      import:    'Import',
      site:      'Site',
      logout:    'Ieși',
    },
    common: {
      save:        'Salvează',
      saving:      'Salvare...',
      cancel:      'Anulează',
      delete:      'Șterge',
      deleting:    'Ștergere...',
      edit:        'Editează',
      add:         'Adaugă',
      search:      'Căutare',
      refresh:     'Reîncarcă',
      loading:     'Se încarcă...',
      noData:      'Nu există date',
      export:      'Export',
      error:       'Eroare',
      all:         'Toate',
      active:      'Active',
      inactive:    'Inactive',
      new:         'Nou',
      name:        'Nume',
      email:       'Email',
      phone:       'Telefon',
      company:     'Companie',
      address:     'Adresă',
      notes:       'Note',
      date:        'Data',
      type:        'Tip',
      status:      'Status',
      price:       'Preț',
      stock:       'Stoc',
      category:    'Categorie',
      brand:       'Brand',
      description: 'Descriere',
      image:       'Imagine',
      of:          'din',
      selected:    'selectați',
      clearSel:    'Deselectează tot',
      noResults:   'Niciun rezultat',
      openInSite:  'Deschide pe site',
    },
    clients: {
      title:            'Clienți',
      searchPlaceholder:'Caută după nume, email, companie...',
      filterCompany:    'Pers. juridice',
      filterIndividual: 'Pers. fizice',
      exportCsv:        'CSV',
      copyEmail:        'Copiază email',
      newsletter:       'Newsletter',
      typeCompany:      'Persoană juridică',
      typeIndividual:   'Persoană fizică',
      deleteConfirm:    'Ștergeți clientul?',
      deleted:          'Client șters',
      errorDelete:      'Eroare la ștergere',
      copied:           'Copiat',
      clientsWord:      'clienți',
      clearSel:         'Deselectează tot',
      noData:           'Niciun client încă. Vor apărea după prima înregistrare.',
      noResults:        'Niciun rezultat',
      newsletterTitle:  'Trimitere ofertă',
      recipients:       'Destinatari',
      selectedLabel:    'selectați',
      allLabel:         'toți din listă',
      emailSubject:     'Subiect email',
      openInEmail:      'Deschide în email',
      copyBcc:          'Copiază BCC',
      bccNote:          'Butonul va deschide clientul dvs. de email (Outlook / Gmail) cu adresele completate în câmpul BCC. Scrisoarea trebuie scrisă și trimisă manual. Pentru newsletter în masă folosiți MailChimp / SendGrid.',
      colName:          'Nume / Companie',
      colEmail:         'Email',
      colPhone:         'Telefon',
      colType:          'Tip',
      colDate:          'Data',
      colAddress:       'Adresă',
      colNotes:         'Note',
      colId:            'ID',
    },
    requests: {
      title:            'Cereri',
      searchPlaceholder:'Caută după nume, email, companie...',
      statusNew:        'Nouă',
      statusInProgress: 'În lucru',
      statusDone:       'Finalizată',
      statusCancelled:  'Anulată',
      deleteConfirm:    'Ștergeți cererea?',
      deleted:          'Cerere ștearsă',
      noData:           'Nicio cerere încă',
      noResults:        'Niciun rezultat',
      items:            'produse',
      totalPrice:       'Total',
      deliveryAddress:  'Adresa de livrare',
      orderItems:       'Compoziția cererii',
      clientName:       'Client',
      clientCompany:    'Companie',
      colDate:          'Data',
      colStatus:        'Status',
      colTotal:         'Total',
      colItems:         'Produse',
      noTableMsg:       'Tabelul',
      noTableDesc:      'nu există în Supabase. Rulați SQL-ul de mai jos:',
      showSql:          'Afișează SQL',
      hideSql:          'Ascunde SQL',
      statusUpdated:    'Statut actualizat',
      filterAll:        'Toate',
      cartItems:        'Produse',
      total:            'Total',
      notes:            'Notă',
      clientComment:    'Comentariul clientului',
      adminComment:     'Comentariul administratorului',
      adminCommentPlaceholder: 'Adaugă comentariu...',
      saveComment:      'Adaugă comentariu',
      noComment:        '—',
      delete:           'Șterge cererea',
      client:           'Client',
      status:           'Statut',
      nothingFound:     'Niciun rezultat',
      empty:            'Nicio cerere încă',
      noItems:          'Niciun produs',
    },
    products: {
      title:          'Produse',
      newBtn:         'Produs nou',
      editTitle:      'Editare produs',
      newTitle:       'Produs nou',
      nameRoLabel:    'Denumire RO',
      nameRuLabel:    'Denumire RU',
      namePlaceholder:'Denumire în română',
      nameRuPlaceholder:'Название на русском',
      descRoLabel:    'Descriere RO',
      descRuLabel:    'Descriere RU',
      descRoPlaceholder:'Descriere detaliată a produsului în română...',
      descRuPlaceholder:'Подробное описание на русском...',
      subcategory:    'Subcategorie',
      noSubcat:       '— niciuna —',
      unit:           'Unitate',
      sku:            'SKU / Cod articol',
      priceMdl:       'Preț MDL',
      stockQty:       'Stoc (buc)',
      activeLabel:    'Activ (vizibil)',
      inactiveLabel:  'Inactiv (ascuns)',
      featuredLabel:  'Recomandat pe pagina principală',
      notFeaturedLabel:'Nu este recomandat',
      youtubeUrl:     'URL YouTube',
      imageNote:      'max 4 · prima = principală',
      imageMainBadge: 'Principal',
      imageSlot:      'Foto',
      deleteProduct:  'Șterge produsul',
      deleteConfirm:  'Ești sigur? Produsul va fi șters definitiv.',
      deleted:        'Produs șters.',
      saved:          'Produs adăugat!',
      updated:        'Produs actualizat!',
      nameRequired:   'Introduceți numele produsului',
      catRequired:    'Selectați categoria',
      allCategories:  'Toate categoriile',
      allFilter:      'Toate',
      activeFilter:   'Active',
      inactiveFilter: 'Inactive',
      reload:         'Reîncarcă',
      colProduct:     'Produs',
      colCategory:    'Categorie',
      colPrice:       'Preț MDL',
      colStock:       'Stoc',
      colActive:      'Activ',
      colFeatured:    'Rec.',
      of:             'din',
      noData:         'Niciun produs găsit',
      selectCat:      'Selectează...',
      selectSubcat:   'Niciuna',
      pageProduct:    'Pagina produsului',
    },
    brands: {
      title:          'Branduri',
      newBtn:         'Brand nou',
      editTitle:      'Editare brand',
      newTitle:       'Brand nou',
      nameLabel:      'Nume brand',
      slugLabel:      'Slug (URL)',
      countryRoLabel: 'Țară (RO)',
      countryRuLabel: 'Țară (RU)',
      flagLabel:      'Steag (emoji)',
      foundedLabel:   'An fondare',
      segmentRoLabel: 'Segment (RO)',
      segmentRuLabel: 'Segment (RU)',
      taglineRoLabel: 'Slogan (RO)',
      taglineRuLabel: 'Slogan (RU)',
      websiteLabel:   'Website',
      websiteUrlLabel:'URL website',
      descRoLabel:    'Descriere (RO)',
      descRuLabel:    'Descriere (RU)',
      logoLabel:      'Logo',
      bannerDesktop:  'Banner (Desktop)',
      bannerMobile:   'Banner (Mobile)',
      deleteConfirm:  'Ștergeți brandul?',
      deleted:        'Brand șters',
      saved:          'Brand salvat!',
      productsWord:   'produse',
      noData:         'Niciun brand încă. Adăugați primul.',
      searchPlaceholder:'Caută brand...',
      loadLogo:       'Încarcă logo',
      newBrand:       'Brand nou',
      editBrand:      'Editare brand',
      brandName:      'Nume brand',
      descriptions:   'Descriere',
      countryInfo:    'Țară / An',
      segment:        'Segment / Site',
      banners:        'Bannere',
      active:         'activ',
      hidden:         'ascuns',
      noBrands:       'Niciun brand încă',
      noResults:      'Niciun rezultat',
      saving:         'Se salvează…',
      create:         'Creează brand',
      save:           'Salvează',
      delete:         'Șterge',
      founded:        'An fond.',
    },
    banners: {
      title:          'Bannere',
      newBtn:         'Banner nou',
      editTitle:      'Editare banner',
      newTitle:       'Banner nou',
      deleteConfirm:  'Ștergeți bannerul?',
      deleted:        'Banner șters',
      saved:          'Banner salvat!',
      titleRoLabel:   'Titlu (RO)',
      titleRuLabel:   'Titlu (RU)',
      subtitleRoLabel:'Subtitlu (RO)',
      subtitleRuLabel:'Subtitlu (RU)',
      ctaRoLabel:     'Buton (RO)',
      ctaRuLabel:     'Buton (RU)',
      linkLabel:      'Link',
      sortOrder:      'Ordine',
      activeLabel:    'Activ',
      imageLabel:     'Imagine',
      noData:         'Niciun banner încă. Creați primul.',
      noTable:        'Tabelul banners nu există în Supabase.',
      noTableDesc:    'Rulați SQL-ul din Supabase Dashboard → SQL Editor:',
      showSql:        'Afișează SQL',
      hideSql:        'Ascunde SQL',
    },
    categories: {
      title:          'Categorii',
      newCat:         'Categorie nouă',
      newSub:         'Subcategorie nouă',
      editCat:        'Editare categorie',
      editSub:        'Editare subcategorie',
      deleteConfirm:  'Ștergeți?',
      deleted:        'Șters',
      saved:          'Salvat',
      nameRoLabel:    'Denumire (RO)',
      nameRuLabel:    'Denumire (RU)',
      descRoLabel:    'Descriere (RO)',
      descRuLabel:    'Descriere (RU)',
      slugLabel:      'Slug',
      sortLabel:      'Ordine sortare',
      subcategories:  'Subcategorii',
      addSubcat:      'Adaugă subcategorie',
      noData:         'Nicio categorie. Creați prima.',
      noTable:        'Tabelele de categorii nu există.',
    },
    featured: {
      title:          'Recomandate',
      searchPlaceholder:'Caută produs...',
      tabAll:         'Toate produsele',
      tabFeatured:    'Recomandate',
      allCategories:  'Toate categoriile',
      noFeatured:     'Niciun produs recomandat',
      noResults:      'Niciun rezultat',
      added:          'adăugat în Recomandate',
      removed:        'eliminat din Recomandate',
      errorSave:      'Eroare la salvare',
      countLabel:     'recomandate',
      reload:         'Reîncarcă',
    },
    import: {
      title:          'Import produse',
      dropzone:       'Trageți fișierul .xlsx sau .csv, sau faceți clic pentru a selecta',
      formatNote:     'Sunt acceptate formatele .xlsx / .csv',
      preview:        'Previzualizare',
      importBtn:      'Importă',
      importing:      'Import...',
      successWord:    'produse importate',
      errorsWord:     'erori',
      downloadTemplate:'Descarcă șablonul',
      columns:        'Coloane:',
      clearBtn:       'Șterge',
      rowsCount:      'rânduri în fișier',
    },
    hub: {
      productsTitle:  'Produse',
      productsDesc:   'Adaugă, editează, șterge produse. Încarcă imagini. Gestionează stocuri, prețuri, descrieri.',
      brandsTitle:    'Branduri',
      brandsDesc:     'Administrare branduri și producători de echipamente sportive.',
      bannersTitle:   'Bannere',
      bannersDesc:    'Administrare slider pe pagina principală.',
      categoriesTitle:'Categorii',
      categoriesDesc: 'Administrare categorii și subcategorii catalog.',
      featuredTitle:  'Recomandate',
      featuredDesc:   'Selectați produse pentru vitrina de pe pagina principală.',
      importTitle:    'Import',
      importDesc:     'Import în masă produse din fișier Excel/CSV.',
      contactsTitle:  'Contacte',
      contactsDesc:   'Telefon, email, adresă, ore de lucru și linkuri rețele sociale.',
      popupTitle:     'Promo-popup',
      popupDesc:      'Fereastră pop-up cu promoție sau anunț important pe site.',
      faqTitle:       'FAQ',
      faqDesc:        'Întrebări frecvente — afișate pe pagina «Despre noi».',
      servicesTitle:  'Pagini servicii',
      servicesDesc:   'Texte, statistici și pachete pentru paginile «La cheie» și «Service».',
      maintenanceTitle:    'Service & Mentenanță',
      maintenanceDesc:     'Conținut pagina «Mentenanță» — tarife, servicii, FAQ.',
      contentPagesTitle:   'Pagini footer',
      contentPagesDesc:    'Editare text pagini: Condiții, Livrare, Confidențialitate.',
      totalLabel:     'Total produse',
      activeLabel:    'active',
      inactiveLabel:  'inactive',
      featuredLabel:  'recomandate',
      noImageLabel:   'fără foto',
      outOfStockLabel:'epuizate',
      statsTitle:     'Statistici catalog',
      // tabs
      tabClients:     'Clienți',
      tabProducts:    'Produse',
      tabContent:     'Conținut',
      // client-section cards
      requestsTitle:  'Cereri',
      requestsDesc:   'Vizualizează și procesează cererile de cumpărare de la clienți.',
      clientsTitle:   'Clienți',
      clientsDesc:    'Baza utilizatorilor înregistrați. Trimitere e-mail, export contacte.',
      emailTitle:     'Notificări Email',
      emailDesc:      'Configurare șabloane și integrare EmailJS pentru răspunsuri automate.',
    },
  },
} as const;

export type AdminTranslations = typeof T.ru;

// ─── Context ──────────────────────────────────────────────────────────────────
interface AdminLangCtx {
  lang: AdminLang;
  setLang: (l: AdminLang) => void;
  t: AdminTranslations;
}

const AdminLangContext = createContext<AdminLangCtx>({
  lang: 'ru',
  setLang: () => {},
  t: T.ru,
});

const STORAGE_KEY = 'admin-ui-lang';

export function AdminLangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<AdminLang>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved === 'ru' || saved === 'ro') return saved;
    } catch {}
    return 'ru';
  });

  const setLang = (l: AdminLang) => {
    setLangState(l);
    try { localStorage.setItem(STORAGE_KEY, l); } catch {}
  };

  return (
    <AdminLangContext.Provider value={{ lang, setLang, t: T[lang] as AdminTranslations }}>
      {children}
    </AdminLangContext.Provider>
  );
}

export function useAdminLang() {
  return useContext(AdminLangContext);
}
